name: meditrack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated Firebase dependencies to potentially newer stable versions
  firebase_core: ^3.2.0 # Tetap di versi ini jika tidak ada versi yang lebih baru
  firebase_auth: ^5.2.0 # Tetap di versi ini jika tidak ada versi yang lebih baru
  cloud_firestore: ^5.2.0 # Tetap di versi ini jika tidak ada versi yang lebih baru
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/meditrack_logo.png
    - assets/doctor_illustration.png
