// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxr0NLk_4pivBptywQ2n-Q1b7NJo3r_QY',
    appId: '1:512209517718:web:06834f732575d5651bd6b7',
    messagingSenderId: '512209517718',
    projectId: 'meditrack-c4510',
    authDomain: 'meditrack-c4510.firebaseapp.com',
    storageBucket: 'meditrack-c4510.firebasestorage.app',
    measurementId: 'G-5FSX1KBRC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6sEnQ-1b7ZHmWhENgDA538cLUtti-8A0',
    appId: '1:512209517718:android:e232320a49601f271bd6b7',
    messagingSenderId: '512209517718',
    projectId: 'meditrack-c4510',
    storageBucket: 'meditrack-c4510.firebasestorage.app',
  );

}